### PR TITLE
DSL for MPS jars

### PR DESCRIPTION
**Pull request by sergej-koscejev**
Introduce a simple inline DSL for describing MPS jars to publish

### CODE REVIEW

**Comment by sergej-koscejev** [comment]
Alternatively, maybe we should get rid of these jars altogether? It may make life more difficult for Maven users but we will never publish all possible jars so it seems like we're solving a problem we can't solve.

Anyway, my primary motivation for this PR was to change the build to use `mpsVersion` lazily, so that it could be imported into IDEA even if no explicit version is defined, but I then realized that we have conditional publications (mps-messaging is published only for MPS version below 2022.3) and this is not straightforward to implement. So I haven't reached the goal yet, but I think that the DSL is nevertheless worth introducing.

**Review by alexanderpann — APPROVED** [review]
I think it is still useful to publish the most common JARs and the DSL looks quite useful.  I also run into the case in the past, that some JARs that I needed were not published. Can we maybe provide some instructions for at least Gradle users how they can get the remaining JARs themselves?

**Comment by sergej-koscejev** [comment]
> Can we maybe provide some instructions for at least Gradle users how they can get the remaining JARs themselves?

These instructions are already part of README.md.

**Comment by alexanderpann** [comment]
Oh, I didn't check the README. Thanks.

**Pull request merged**
