### PR TITLE
Publish 2023.3 RC1

### PR DESCRIPTION
**Pull request by sergej-koscejev**

### CODE REVIEW

**Comment by arimer** [comment]
I think it is the first time we re-publish a RC. What is the motivation for it?

Anyway, the publication went already through becaue your branch name was mathcing our branch name conditions: https://github.com/mbeddr/build.publish.mps/blob/f6c3f943f005c14e2ad60ce89e53d32d1173fb05/.github/workflows/gradle.yml#L22

**Comment by sergej-koscejev** [comment]
I want to migrate mps-qa to the latest prerelease of MPS but I need to migrate it to 2023.3 first and I’m working on doing it programmatically.

I don’t think it’s the first time we publish a RC/EAP (there’s code to support EAPs in the script) but it’s true that we didn’t do it for a long time.

**Comment by sergej-koscejev** [comment]
> Anyway, the publication went already through becaue your branch name was mathcing our branch name conditions:

I was counting on it :) I think the GitHub Actions need some improvement.

**Comment by arimer** [comment]
> I was counting on it :) I think the GitHub Actions need some improvement.

Agreed, do you mind creating an issue for it?

**Review by arimer — APPROVED** [review]
Fine for now.

**Pull request merged**
